version: '3.8'

services:

  db:
    container_name: teams-api-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d exampledb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - teams-api-network
    ports:
      - 5433:5432

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: db
      DATABASE_PORT: 5432
    networks:
      - teams-api-network

networks:
  teams-api-network:
    driver: bridge
