version: '3.8'

services:

  db:
    container_name: teams-api-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gorm" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
