## TODOS
#
# - release on kind/integration tests
# - publish to ghcr or w/e our registry is long term
#
---
version: 2.1

globals:
  - &context empc-lab

parameters:
  image-name:
    description: Image name displayed on Github Packages
    type: string
    default: di-iam-operator

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

commands:
  install-cosign:
    description: Install cosign
    parameters:
      cosign-version:
        description: Must provide the release version of cosign
        type: string
        default: v1.6.0
    steps:
      - run:
          name: Install cosign
          command: |
            wget "https://github.com/sigstore/cosign/releases/download/<< parameters.cosign-version >>/cosign-linux-amd64"
            sudo mv cosign-linux-amd64 /usr/local/bin/cosign
            sudo chmod +x /usr/local/bin/cosign

executors:
  docker-golang-executor:
    docker:
      - image: cimg/go:1.20.4

jobs:
  golang-static:
    executor: docker-golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ arch }}-{{ checksum "go.sum"  }}
      - run:
          name: go lint
          environment:
            GOCACHE: /home/circleci/.cache/go-build
            GOLANGCI_LINT_CACHE: /home/circleci/.cache/lint
          command: |
            golangci-lint version
            golangci-lint run ./...  -v
      - save_cache:
          key: go-mod-{{ arch }}-{{ checksum "go.sum"  }}
          paths:
            - /home/circleci/.cache/go-build
            - /home/circleci/.cache/lint
            - /home/circleci/go/pkg/mod
      - run:
          name: Run Tests
          command: |
            make test
  docker:
    executor: docker-golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ arch }}-{{ checksum "go.sum"  }}
      - run:
          name: build image 
          command: |
            make build
      - run:
          name: push docker image
          command: |
            make push
  release:
    executor: amd64
    steps:
      - checkout
      - cosign/install
      - set-environment
      - run:
          name: fetch keys for signing
          command: |
            echo "op://empc-lab/svc-cosign-private-key/notesPlain" > cosign.key.env
            echo "op://empc-lab/svc-cosign-public-key/notesPlain" > cosign.pub.env
            op inject -i cosign.key.env -o cosign.key
            op inject -i cosign.pub.env -o cosign.pub
      - restore_cache:
          keys:
            - go-mod-{{ arch }}-{{ checksum "go.sum"  }}
      - run:
          name: Use goreleaser to build and publish executables
          command: |
            curl -sL https://git.io/goreleaser | bash
      - run: 
          name: validate signature
          command: cosign verify -key cosign.pub twdps/lab-api-teams
      - do/prune-dockerhub:
          repository: twdps/lab-api-teams
          tag-filter: dev
             
workflows:
  lab-api-teams-pipeline:
    jobs:
      - golang-static:
          name: golang static 
          context: *context
          filters: *on-push-main
