apiVersion: batch/v1
kind: Job
metadata:
  name: lab-api-teams-migrate
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: twdps/lab-api-teams-migrate:{{ .Values.image.tag }}
          env:
          - name: DATABASE_URL
            value: {{ .Values.database.url }}
          - name: DATABASE_PORT
            value: {{ .Values.database.port | quote }}
      restartPolicy: Never
  backoffLimit: 4
