### Create a team
POST http://localhost:8080/teams HTTP/1.1
content-type: application/json

{
    "TeamID": "team-sapphire",
    "TeamType": "normal",
    "TeamDescription": "Sapphire frontend team",
    "TeamRAM": 32,
    "TeamCPU": 12,
    "TeamRamLimit": 64,
    "TeamCpuLimit": 24
}

### List teams
GET http://localhost:8080/teams HTTP/1.1

### Create a namespace
POST http://localhost:8080/namespaces HTTP/1.1
content-type: application/json

{
    "NamespaceID": "account-dev",
    "NamespaceType": "standard", 
    "NamespaceTeamID": "team-sapphire",
    "NamespaceRam": 32,
    "NamespaceCpu": 12, 
    "NamespaceInMesh": true,
    "NamespaceFromDefault": false
}

### List namespaces
GET http://localhost:8080/namespaces HTTP/1.1
content-type: application/json

### List namespaces by standard type
GET http://localhost:8080/namespaces?filters[namespace_type]=standard
content-type: application/json

### List namespaces by master type
GET http://localhost:8080/namespaces?filters[namespace_type]=master
content-type: application/json

### List namespaces with paginator
GET http://localhost:8080/namespaces?page=1&maxResults=10
content-type: application/json

### List namespaces by filter with paginator
GET http://localhost:8080/namespaces?filters[namespace_team_id]=team-sapphire&page=1&maxResults=10
content-type: application/json